stages:
  - build
  - deploy

variables:
  REPO_NAME: reactapp
  IMAGE_TAG: latest
  REPO_URL: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME
  IMAGE_NAME_WITH_TAG: $REPO_URL:$IMAGE_TAG

run:
  stage: build
  image: node:lts-alpine
  script:
    - cd app/
    - npm install
    - npm run build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/app/build
    expire_in: 1 week

docker_image:
  stage: build
  image: docker:stable
  needs: [run]
  services:
    - docker:dind
  before_script:
    - apk add --no-cache python3 py3-pip
    - pip3 install awscli
    - aws ecr get-login-password --region $AWS_REGION |
      docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  script:
    - docker build -t $IMAGE_NAME_WITH_TAG .
    - docker push $IMAGE_NAME_WITH_TAG
  when: manual