variables:
  TF_ROOT: ${CI_PROJECT_DIR}
  TF_STATE_NAME: default

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/

image:
  name: "$CI_TEMPLATE_REGISTRY_HOST/gitlab-org/terraform-images/releases/1.4:v1.0.0"

stages:
  - validate
  - build
  - deploy
  - cleanup

npm_run:
  stage: validate
  image: node:lts-alpine
  script:
    - cd app/
    - npm install
    - npm run build

terraform_validate:
  stage: validate
  needs: [npm_run]
  script:
    - gitlab-terraform validate

docker_build_image:
  stage: build
  image: docker:stable
  needs: [npm_run]
  services:
    - docker:dind
  before_script:
    - apk add --no-cache python3 py3-pip
    - pip3 install awscli
    - aws ecr get-login-password --region $TF_VAR_region |
      docker login --username AWS --password-stdin $TF_VAR_accountID.dkr.ecr.$TF_VAR_region.amazonaws.com
  script:
    - docker build -t $TF_VAR_imageURL .
    - docker push $TF_VAR_imageURL
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $DOCKER_IMAGE_AUTO_DEPLOY == "true"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual

terraform_build:
  stage: build
  needs: [terraform_validate]
  environment:
    name: $TF_STATE_NAME
    action: prepare
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  resource_group: ${TF_STATE_NAME}
  artifacts:
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

terraform_deploy:
  stage: deploy
  needs: [terraform_build]
  environment:
    name: $TF_STATE_NAME
    action: start
  script:
    - gitlab-terraform apply
  resource_group: ${TF_STATE_NAME}
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $TF_AUTO_DEPLOY == "true"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual

terraform_destroy:
  stage: cleanup
  needs: [terraform_deploy]
  environment:
    name: $TF_STATE_NAME
  script:
    - gitlab-terraform destroy
  resource_group: ${TF_STATE_NAME}
  when: manual
