apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment
  namespace: reactapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
        - name: reactapp
          image: scnplt/reactapp:v1
          ports:
            - containerPort: 3000