apiVersion: v1
kind: Service
metadata:
  name: reactapp-np-service
  namespace: reactapp
spec:
  type: NodePort
  selector:
    app: reactapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
